name: sri_kamakoti
description: Official mobile application for Sri Kanchi Kamakoti Peetam

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  redux: ^3.0.0
  flutter_redux: ^0.5.3
  redux_logging: ^0.3.0
  background_fetch: ^0.1.0
  dio: ^2.1.12
  flutter_local_notifications: ^0.7.1+3
  flutter_custom_tabs: ^0.6.0
  url_launcher: ^5.0.5
  pk_skeleton:
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/food.jpg
    - assets/black_gradient.png